/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mikir;



/**
 *
 * @author Gatra
 */
public class Content extends javax.swing.JFrame {
    /**
     * Creates new form Content
     */
    private int biaya,n=1;
    
    public Content() {
        initComponents();
        tfKendaraan.setVisible(false);
    }
    
    public void hitung(){
         //deklarasi variabel
        int masuk, keluar, lama, harga;
        
        //inisialisasi variabel
        masuk = Integer.parseInt(tfJamMasuk.getText());
        keluar = Integer.parseInt(tfJamKeluar.getText());
        
        //proses
        lama = keluar - masuk;
        
        //pengkondisian
        
        if(rbMobil.isSelected()){
            tfKendaraan.setText("Mobil");
            harga = 4000;
        }else {
            tfKendaraan.setText("Motor");
            harga = 2000;
        }
        
        biaya = lama*harga;
        if(biaya > 20000){
            biaya = 20000;
        }else{
            biaya = lama*harga;
        }
        
        //setText
        BiayaParkir.setText(String.valueOf("Rp. " + biaya));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenPanel = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        KetPanel = new javax.swing.JPanel();
        rbMobil = new javax.swing.JRadioButton();
        lbJamMasuk = new javax.swing.JLabel();
        rbMotor = new javax.swing.JRadioButton();
        lbNoPolisi = new javax.swing.JLabel();
        lbJnsKendaraan = new javax.swing.JLabel();
        tfJamMasuk = new javax.swing.JTextField();
        lbJamKeluar = new javax.swing.JLabel();
        tfJamKeluar = new javax.swing.JTextField();
        tfNoPolisi = new javax.swing.JTextField();
        lbNoAntrean = new javax.swing.JLabel();
        tfNoAntrean = new javax.swing.JTextField();
        lbBiayaParkir = new javax.swing.JLabel();
        lbPembayaran = new javax.swing.JLabel();
        tfPembayaran = new javax.swing.JTextField();
        lbKembalian = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        btnReset = new javax.swing.JLabel();
        BiayaParkir = new javax.swing.JLabel();
        Kembalian = new javax.swing.JLabel();
        tfKendaraan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContenPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContenPanel.setPreferredSize(new java.awt.Dimension(586, 258));

        Judul.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("Admin Parkir");

        KetPanel.setBackground(new java.awt.Color(0, 255, 51));
        KetPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true));
        KetPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbMobil.setBackground(new java.awt.Color(0, 255, 51));
        rbMobil.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        rbMobil.setText("Mobil");
        rbMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMobilMouseClicked(evt);
            }
        });
        KetPanel.add(rbMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 52, -1, -1));

        lbJamMasuk.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lbJamMasuk.setText("Jam Masuk    :");
        KetPanel.add(lbJamMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 51, -1, 22));

        rbMotor.setBackground(new java.awt.Color(0, 255, 51));
        rbMotor.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        rbMotor.setText("Motor");
        rbMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMotorMouseClicked(evt);
            }
        });
        KetPanel.add(rbMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 75, -1, -1));

        lbNoPolisi.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lbNoPolisi.setText("No. Polisi      :");
        KetPanel.add(lbNoPolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 23, -1, 22));

        lbJnsKendaraan.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lbJnsKendaraan.setText("Jenis Kendaraan :");
        KetPanel.add(lbJnsKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 51, -1, 22));
        KetPanel.add(tfJamMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 52, 114, -1));

        lbJamKeluar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lbJamKeluar.setText("Jam Keluar   :");
        KetPanel.add(lbJamKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 79, -1, 22));

        tfJamKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfJamKeluarKeyReleased(evt);
            }
        });
        KetPanel.add(tfJamKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 80, 114, -1));
        KetPanel.add(tfNoPolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 24, 114, -1));

        lbNoAntrean.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lbNoAntrean.setText("No. Antrean  : ");
        KetPanel.add(lbNoAntrean, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 23, -1, 22));

        tfNoAntrean.setEditable(false);
        tfNoAntrean.setText("1");
        KetPanel.add(tfNoAntrean, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 24, 114, -1));

        lbBiayaParkir.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lbBiayaParkir.setText("Biaya Parkir :");
        KetPanel.add(lbBiayaParkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 121, -1, 22));

        lbPembayaran.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lbPembayaran.setText("Pembayaran   :");
        KetPanel.add(lbPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 121, -1, 22));

        tfPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPembayaranActionPerformed(evt);
            }
        });
        tfPembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPembayaranKeyReleased(evt);
            }
        });
        KetPanel.add(tfPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 122, 114, -1));

        lbKembalian.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lbKembalian.setText("Kembalian    :");
        KetPanel.add(lbKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 149, -1, 22));

        btnSimpan.setBackground(new java.awt.Color(255, 245, 0));
        btnSimpan.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnSimpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnSimpan.setOpaque(true);
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        KetPanel.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 161, 58, 22));

        btnReset.setBackground(new java.awt.Color(255, 51, 40));
        btnReset.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReset.setText("Reset");
        btnReset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnReset.setOpaque(true);
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        KetPanel.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 161, 58, 22));

        BiayaParkir.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        BiayaParkir.setText("Rp. -");
        KetPanel.add(BiayaParkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 114, 22));

        Kembalian.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        Kembalian.setText("Rp. -");
        KetPanel.add(Kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 114, 22));

        tfKendaraan.setEditable(false);
        tfKendaraan.setBackground(new java.awt.Color(255, 255, 255));
        tfKendaraan.setForeground(new java.awt.Color(255, 255, 255));
        tfKendaraan.setBorder(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gatra\\Downloads\\icons8-back-arrow-50.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ContenPanelLayout = new javax.swing.GroupLayout(ContenPanel);
        ContenPanel.setLayout(ContenPanelLayout);
        ContenPanelLayout.setHorizontalGroup(
            ContenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addGroup(ContenPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(tfKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContenPanelLayout.setVerticalGroup(
            ContenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenPanelLayout.createSequentialGroup()
                .addGroup(ContenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(tfKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(ContenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPembayaranActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        n++;
        tfNoAntrean.setText(String.valueOf(n));
        History hs = new History();
        hs.setVisible(true);
        hs.AddToTable(new Object[]{
                                    tfNoAntrean.getText(),
                                    tfKendaraan.getText(),
                                    tfNoPolisi.getText(),
                                    tfJamMasuk.getText(),
                                    tfJamKeluar.getText()
                                   });
        
        tfJamMasuk.setText("");
        tfJamKeluar.setText("");
        tfNoPolisi.setText("");
        tfPembayaran.setText("");
        tfKendaraan.setText("");
        rbMobil.setSelected(false);
        rbMotor.setSelected(false);
        BiayaParkir.setText("Rp.-");
        Kembalian.setText("Rp.-");
        
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tfJamKeluarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJamKeluarKeyReleased
        //hitung();
    }//GEN-LAST:event_tfJamKeluarKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tfPembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPembayaranKeyReleased
        int bayar, kembalian;
        
        bayar = Integer.parseInt(tfPembayaran.getText());
        kembalian = bayar - biaya;
        Kembalian.setText(String.valueOf("Rp. "+kembalian));
    }//GEN-LAST:event_tfPembayaranKeyReleased

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        tfJamMasuk.setText("");
        tfJamKeluar.setText("");
        tfNoPolisi.setText("");
        tfPembayaran.setText("");
        tfKendaraan.setText("");
        rbMobil.setSelected(false);
        rbMotor.setSelected(false);
        BiayaParkir.setText("Rp.-");
        Kembalian.setText("Rp.-");
    }//GEN-LAST:event_btnResetMouseClicked

    private void rbMotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMotorMouseClicked
        hitung();
    }//GEN-LAST:event_rbMotorMouseClicked

    private void rbMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMobilMouseClicked
        hitung();
    }//GEN-LAST:event_rbMobilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Content().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BiayaParkir;
    private javax.swing.JPanel ContenPanel;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel Kembalian;
    private javax.swing.JPanel KetPanel;
    private javax.swing.JLabel btnReset;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbBiayaParkir;
    private javax.swing.JLabel lbJamKeluar;
    private javax.swing.JLabel lbJamMasuk;
    private javax.swing.JLabel lbJnsKendaraan;
    private javax.swing.JLabel lbKembalian;
    private javax.swing.JLabel lbNoAntrean;
    private javax.swing.JLabel lbNoPolisi;
    private javax.swing.JLabel lbPembayaran;
    private javax.swing.JRadioButton rbMobil;
    private javax.swing.JRadioButton rbMotor;
    private javax.swing.JTextField tfJamKeluar;
    private javax.swing.JTextField tfJamMasuk;
    private javax.swing.JTextField tfKendaraan;
    private javax.swing.JTextField tfNoAntrean;
    private javax.swing.JTextField tfNoPolisi;
    private javax.swing.JTextField tfPembayaran;
    // End of variables declaration//GEN-END:variables
}
